### ISSUE TITLE
[FEAT] 캘린더 페이지 기능구현

### ISSUE THREAD

**Issue by gyulls2** [gyulls2/Foomee#38]
## 📝 Description
캘린더 페이지의 기능을 구현합니다.
- 상단의 먹었어요 `버튼`을 클릭하면 날짜별로 기록된 총 섭취 칼로리가 캘린더에 표시됩니다.
- `몸무게` 버튼을 누르면 날짜별로 기록된 체중이 캘린더에 표시됩니다.
- 캘린더의 날짜를 선택하고 `선택한 날짜로 이동` 버튼을 클릭하면 `메인 페이지`로 이동하여 해당 날짜의 기록을 보여줍니다.

## ✔️ TODO
- [x]  식사 / 체중 토글버튼 (스타일 변경)
### 체중기록 확인
- [x]  체중 불러오기
- [x]  날짜 아래 text로 세팅
- [x]  체중 기록이 있는 날은 배경색 바꾸기
### 식사기록 확인
- [x]  `total kcal` 게시판 생성 필요
- [x]  식사 불러오기
### 선택한 날짜로 이동 기능
- [x]  오늘로 이동 클릭 시 오늘(메인페이지)로 이동
- [x]  `선택된 날짜를 저장`하는 zustand 스토어 생성 필요
- [x]  선택한 날짜로 이동 클릭 시 스토어 갱신 → 메인페이지에서 선택한 날짜의 기록 보여주기

## 📌 ETC
기타 참고사항을 적어주세요.
