### ISSUE TITLE
[FEAT] openai api 연동

### ISSUE THREAD

**Issue by gyulls2** [gyulls2/Foomee#43]
## 📝 Description
openai api와 통신하여 채팅 기능을 구현합니다.

## ✔️ TODO
- [x] openai api key 발급
- [x] api 통신 로직 추가
- [x] 입력된 식단을 기반으로 한 프롬프트 작성
- [x] 응답 결과 화면에 출력

## 📌 ETC
기타 참고사항을 적어주세요.
