### ISSUE TITLE
[FEAT] 초기 목표 설정 기능

### ISSUE THREAD

**Issue by gyulls2** [gyulls2/Foomee#50]
## 📝 Description
초기 목표 설정 기능을 구현합니다.

## ✔️ TODO
- [x] 초기 목표 설정 기능 구현
- [x] 회원정보 수정 api 사용해 목표 저장
- [x] 목표 설정이 완료되면 자동 로그인 후 메인페이지로 이동

## 📌 ETC
기타 참고사항을 적어주세요.
