### ISSUE TITLE
[FEAT] 통계 페이지 체중 목표, 섭취량 조회

### ISSUE THREAD

**Issue by gyulls2** [gyulls2/Foomee#75]
## 📝 Description
통계 페이지에서 체중 목표와 섭취량을 조회합니다.

## ✔️ TODO
- [x] 유저 데이터 - 시작 체중, 목표 체중 조회
- [x] weight 게시판 - 가장 최근 입력한 체중 조회, 시작 체중과 차이 계산
- [x] nutri 게시판 - 오늘 섭취량 조회

## 📌 ETC
기타 참고사항을 적어주세요.
